# -*- coding: utf-8 -*-
"""readmission_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Xt2Go3qRTIA2q-e5NjltT9wrY-OwqVE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score

# Load data
df = pd.read_csv('/content/sample_readmission_data.csv')

# Encode categorical
df = pd.get_dummies(df, columns=['Gender', 'Diagnosis'], drop_first=True)

# Split
X = df.drop(['Patient_ID', 'Readmitted_Within_30Days'], axis=1)
y = df['Readmitted_Within_30Days']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

# Evaluate
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score

# ✅ Load data
df = pd.read_csv('sample_data/sample_readmission_data.csv')

# ✅ Encode categorical
df = pd.get_dummies(df, columns=['Gender', 'Diagnosis'], drop_first=True)

# ✅ Split
X = df.drop(['Patient_ID', 'Readmitted_Within_30Days'], axis=1)
y = df['Readmitted_Within_30Days']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ✅ Train
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

# ✅ Evaluate
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score

# ✅ Correct file path (after upload)
df = pd.read_csv('/content/sample_readmission_data.csv')  # Adjust filename if different

# ✅ Encode categorical
df = pd.get_dummies(df, columns=['Gender', 'Diagnosis'], drop_first=True)

# ✅ Split
X = df.drop(['Patient_ID', 'Readmitted_Within_30Days'], axis=1)
y = df['Readmitted_Within_30Days']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ✅ Train
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

# ✅ Evaluate
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))